prompt PL/SQL Developer import file
prompt Created on lunes, 20 de agosto de 2018 by mario
set feedback off
set define off
prompt Disabling triggers for ADMINISTRADOR...
alter table ADMINISTRADOR disable all triggers;
prompt Disabling triggers for CANCHA...
alter table CANCHA disable all triggers;
prompt Disabling triggers for EQUIPO...
alter table EQUIPO disable all triggers;
prompt Disabling triggers for RETO...
alter table RETO disable all triggers;
prompt Disabling triggers for MATCH...
alter table MATCH disable all triggers;
prompt Disabling foreign key constraints for CANCHA...
alter table CANCHA disable constraint ADM_ID_FK;
prompt Disabling foreign key constraints for EQUIPO...
alter table EQUIPO disable constraint RETO_FK01;
prompt Disabling foreign key constraints for RETO...
alter table RETO disable constraint CANCHA_ID_FK;
alter table RETO disable constraint EQUIPO1_ID_FK01;
alter table RETO disable constraint EQUIPO2_ID_FK01;
prompt Disabling foreign key constraints for MATCH...
alter table MATCH disable constraint CAN_ID_FK01;
alter table MATCH disable constraint EQU_ID1_FK01;
alter table MATCH disable constraint EQU_ID2_FK01;
prompt Deleting MATCH...
delete from MATCH;
commit;
prompt Deleting RETO...
delete from RETO;
commit;
prompt Deleting EQUIPO...
delete from EQUIPO;
commit;
prompt Deleting CANCHA...
delete from CANCHA;
commit;
prompt Deleting ADMINISTRADOR...
delete from ADMINISTRADOR;
commit;
prompt Loading ADMINISTRADOR...
prompt Table is empty
prompt Loading CANCHA...
prompt Table is empty
prompt Loading EQUIPO...
insert into EQUIPO (equ_id, equ_usu, equ_password, equ_nombre, equ_nom_jug1, equ_nom_jug2, equ_url, equ_tel_jug2, equ_tel_jug1, equ_pts, reto_id)
values (23, 'mario', 'mario', 'liga', 'dfedf', 'dfdsf', null, 3434343, 4334343, 0, null);
commit;
prompt 1 records loaded
prompt Loading RETO...
prompt Table is empty
prompt Loading MATCH...
prompt Table is empty
prompt Enabling foreign key constraints for CANCHA...
alter table CANCHA enable constraint ADM_ID_FK;
prompt Enabling foreign key constraints for EQUIPO...
alter table EQUIPO enable constraint RETO_FK01;
prompt Enabling foreign key constraints for RETO...
alter table RETO enable constraint CANCHA_ID_FK;
alter table RETO enable constraint EQUIPO1_ID_FK01;
alter table RETO enable constraint EQUIPO2_ID_FK01;
prompt Enabling foreign key constraints for MATCH...
alter table MATCH enable constraint CAN_ID_FK01;
alter table MATCH enable constraint EQU_ID1_FK01;
alter table MATCH enable constraint EQU_ID2_FK01;
prompt Enabling triggers for ADMINISTRADOR...
alter table ADMINISTRADOR enable all triggers;
prompt Enabling triggers for CANCHA...
alter table CANCHA enable all triggers;
prompt Enabling triggers for EQUIPO...
alter table EQUIPO enable all triggers;
prompt Enabling triggers for RETO...
alter table RETO enable all triggers;
prompt Enabling triggers for MATCH...
alter table MATCH enable all triggers;
set feedback on
set define on
prompt Done.
